# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build App

on:
  push:
    branches: [ "prod-ec2", "dev" ]
  pull_request:
    branches: [ "prod-ec2", "dev" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - uses: liquibase-github-actions/init-copy@v4.20.0
      with:
        # ProjectCopier object that can be passed in
        # string
        # Optional
        # projectCopier: ""

        # Recursive copy files from the source directory
        # bool
        # Optional
        recursive: "true"

        # Path to the directory where the project files will be created
        # string
        # Optional
        source: "./dist"

        # Source directory where the project files will be copied from
        # string
        # Optional
        target: "/etc/nginx/html/react-rock-papper-scissors"
    
